#!/bin/bash
# PARA Workspace — Remove Tool Plugin
# Usage: ./para remove-tool <name> [--force]
#
# Removes an installed tool plugin and its auto-generated wrapper script.

set -e

# === Resolve paths ===
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CLI_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
COMMANDS_DIR="$SCRIPT_DIR"

# Workspace Root (inherited from parent CLI)
if [ -z "$WORKSPACE_ROOT" ]; then
  echo "❌ Error: WORKSPACE_ROOT not set. Run this via './para remove-tool'."
  exit 1
fi

TOOLS_DIR="$WORKSPACE_ROOT/.para/tools"

# === Parse arguments ===
TOOL_INPUT=""
FORCE_MODE=false

for arg in "$@"; do
  case "$arg" in
    --force|-f)
      FORCE_MODE=true
      ;;
    --help|-h)
      echo "Usage: para remove-tool <name> [--force]"
      echo ""
      echo "  <name>    Tool name (e.g., 'para-graph' or 'graph')"
      echo "  --force   Skip confirmation prompt"
      echo ""
      echo "Examples:"
      echo "  para remove-tool para-graph"
      echo "  para remove-tool graph --force"
      exit 0
      ;;
    -*)
      echo "❌ Error: Unknown option '$arg'"
      exit 1
      ;;
    *)
      if [ -z "$TOOL_INPUT" ]; then
        TOOL_INPUT="$arg"
      else
        echo "❌ Error: Too many arguments."
        exit 1
      fi
      ;;
  esac
done

if [ -z "$TOOL_INPUT" ]; then
  echo "❌ Error: Missing tool name."
  echo "Usage: para remove-tool <name>"
  exit 1
fi

# === Normalize tool name ===
if echo "$TOOL_INPUT" | grep -q "^para-"; then
  TOOL_NAME="${TOOL_INPUT#para-}"
  PARA_TOOL_NAME="$TOOL_INPUT"
else
  TOOL_NAME="$TOOL_INPUT"
  PARA_TOOL_NAME="para-$TOOL_INPUT"
fi

# === Check if installed ===
TOOL_INSTALL_DIR="$TOOLS_DIR/$TOOL_NAME"
WRAPPER_SCRIPT="$COMMANDS_DIR/$TOOL_NAME.sh"

if [ ! -d "$TOOL_INSTALL_DIR" ] && [ ! -f "$WRAPPER_SCRIPT" ]; then
  echo "❌ Error: Tool '$PARA_TOOL_NAME' is not installed."
  exit 1
fi

# === Safety check: only remove auto-generated wrappers (R6) ===
WRAPPER_IS_AUTOGENERATED=false
if [ -f "$WRAPPER_SCRIPT" ]; then
  if head -2 "$WRAPPER_SCRIPT" | grep -q "Auto-generated by PARA Workspace"; then
    WRAPPER_IS_AUTOGENERATED=true
  else
    echo "⚠️  Warning: Wrapper '$WRAPPER_SCRIPT' does NOT have an auto-generated header."
    echo "   This may be a core command — wrapper will NOT be removed."
  fi
fi

# === AI Intelligence detection ===
# Check if tool has installed AI intelligence via manifest
MANIFEST_FILE="$TOOL_INSTALL_DIR/tool.manifest.yml"
AGENTS_DIR="$WORKSPACE_ROOT/.agents"
HAS_AGENTS=false
AGENT_FILES=()

if [ -f "$MANIFEST_FILE" ]; then
  # Check if manifest has agents: block
  if grep -q "^agents:" "$MANIFEST_FILE" 2>/dev/null; then
    # Parse agent targets from manifest (simple grep — no state machine needed for removal)
    while IFS= read -r line; do
      local_target=$(echo "$line" | sed 's/.*target: *//; s/^ *"//; s/" *$//')
      if [ -n "$local_target" ]; then
        AGENT_FILES+=("$local_target")
      fi
    done < <(sed -n '/^agents:/,/^[a-z]/p' "$MANIFEST_FILE" | grep "target:")

    # Check which agent files actually exist in .agents/
    INSTALLED_AGENTS=()
    for af in "${AGENT_FILES[@]}"; do
      for subdir in workflows skills rules; do
        if [ -e "$AGENTS_DIR/$subdir/$af" ]; then
          INSTALLED_AGENTS+=("$AGENTS_DIR/$subdir/$af")
          HAS_AGENTS=true
        fi
      done
    done
  fi
fi

# === Confirmation ===
if [ "$FORCE_MODE" = false ]; then
  echo "🗑  About to remove tool '$PARA_TOOL_NAME':"
  if [ -d "$TOOL_INSTALL_DIR" ]; then
    echo "   Tool dir:   $TOOL_INSTALL_DIR"
  fi
  if [ "$WRAPPER_IS_AUTOGENERATED" = true ]; then
    echo "   Wrapper:    $WRAPPER_SCRIPT"
  fi
  echo ""
  printf "   Continue? [y/N] "
  read -r CONFIRM
  if [ "$CONFIRM" != "y" ] && [ "$CONFIRM" != "Y" ]; then
    echo "Cancelled."
    exit 0
  fi
fi

# === Remove tool ===
if [ -d "$TOOL_INSTALL_DIR" ]; then
  rm -rf "$TOOL_INSTALL_DIR"
  echo "  → Removed tool directory: $TOOL_INSTALL_DIR"
fi

if [ "$WRAPPER_IS_AUTOGENERATED" = true ] && [ -f "$WRAPPER_SCRIPT" ]; then
  rm -f "$WRAPPER_SCRIPT"
  echo "  → Removed wrapper script: $WRAPPER_SCRIPT"
fi

# === AI Intelligence cleanup ===
if [ "$HAS_AGENTS" = true ] && [ ${#INSTALLED_AGENTS[@]} -gt 0 ]; then
  echo ""
  echo "  ⚠️  Tool '$PARA_TOOL_NAME' has installed AI intelligence:"
  for agent_path in "${INSTALLED_AGENTS[@]}"; do
    echo "    - $agent_path"
  done
  echo ""
  if [ "$FORCE_MODE" = true ]; then
    REMOVE_AGENTS="y"
  else
    printf "  Remove AI intelligence too? (y/n): "
    read -r REMOVE_AGENTS
  fi
  if [ "$REMOVE_AGENTS" = "y" ] || [ "$REMOVE_AGENTS" = "Y" ]; then
    for agent_path in "${INSTALLED_AGENTS[@]}"; do
      rm -rf "$agent_path"
      echo "  → Removed: $agent_path"
    done
  else
    echo "  ⏭️  AI intelligence kept."
  fi
fi

echo ""
echo "✅ Successfully removed $PARA_TOOL_NAME"
