#!/bin/bash
# PARA Workspace — Remove Tool Plugin
# Usage: ./para remove-tool <name> [--force]
#
# Removes an installed tool plugin and its auto-generated wrapper script.

set -e

# === Resolve paths ===
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CLI_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
COMMANDS_DIR="$SCRIPT_DIR"

# Workspace Root (inherited from parent CLI)
if [ -z "$WORKSPACE_ROOT" ]; then
  echo "❌ Error: WORKSPACE_ROOT not set. Run this via './para remove-tool'."
  exit 1
fi

TOOLS_DIR="$WORKSPACE_ROOT/.para/tools"

# === Parse arguments ===
TOOL_INPUT=""
FORCE_MODE=false

for arg in "$@"; do
  case "$arg" in
    --force|-f)
      FORCE_MODE=true
      ;;
    --help|-h)
      echo "Usage: para remove-tool <name> [--force]"
      echo ""
      echo "  <name>    Tool name (e.g., 'para-graph' or 'graph')"
      echo "  --force   Skip confirmation prompt"
      echo ""
      echo "Examples:"
      echo "  para remove-tool para-graph"
      echo "  para remove-tool graph --force"
      exit 0
      ;;
    -*)
      echo "❌ Error: Unknown option '$arg'"
      exit 1
      ;;
    *)
      if [ -z "$TOOL_INPUT" ]; then
        TOOL_INPUT="$arg"
      else
        echo "❌ Error: Too many arguments."
        exit 1
      fi
      ;;
  esac
done

if [ -z "$TOOL_INPUT" ]; then
  echo "❌ Error: Missing tool name."
  echo "Usage: para remove-tool <name>"
  exit 1
fi

# === Normalize tool name ===
if echo "$TOOL_INPUT" | grep -q "^para-"; then
  TOOL_NAME="${TOOL_INPUT#para-}"
  PARA_TOOL_NAME="$TOOL_INPUT"
else
  TOOL_NAME="$TOOL_INPUT"
  PARA_TOOL_NAME="para-$TOOL_INPUT"
fi

# === Check if installed ===
TOOL_INSTALL_DIR="$TOOLS_DIR/$TOOL_NAME"
WRAPPER_SCRIPT="$COMMANDS_DIR/$TOOL_NAME.sh"

if [ ! -d "$TOOL_INSTALL_DIR" ] && [ ! -f "$WRAPPER_SCRIPT" ]; then
  echo "❌ Error: Tool '$PARA_TOOL_NAME' is not installed."
  exit 1
fi

# === Safety check: only remove auto-generated wrappers (R6) ===
WRAPPER_IS_AUTOGENERATED=false
if [ -f "$WRAPPER_SCRIPT" ]; then
  if head -2 "$WRAPPER_SCRIPT" | grep -q "Auto-generated by PARA Workspace"; then
    WRAPPER_IS_AUTOGENERATED=true
  else
    echo "⚠️  Warning: Wrapper '$WRAPPER_SCRIPT' does NOT have an auto-generated header."
    echo "   This may be a core command — wrapper will NOT be removed."
  fi
fi

# === Confirmation ===
if [ "$FORCE_MODE" = false ]; then
  echo "🗑  About to remove tool '$PARA_TOOL_NAME':"
  if [ -d "$TOOL_INSTALL_DIR" ]; then
    echo "   Tool dir:   $TOOL_INSTALL_DIR"
  fi
  if [ "$WRAPPER_IS_AUTOGENERATED" = true ]; then
    echo "   Wrapper:    $WRAPPER_SCRIPT"
  fi
  echo ""
  printf "   Continue? [y/N] "
  read -r CONFIRM
  if [ "$CONFIRM" != "y" ] && [ "$CONFIRM" != "Y" ]; then
    echo "Cancelled."
    exit 0
  fi
fi

# === Remove ===
if [ -d "$TOOL_INSTALL_DIR" ]; then
  rm -rf "$TOOL_INSTALL_DIR"
  echo "  → Removed tool directory: $TOOL_INSTALL_DIR"
fi

if [ "$WRAPPER_IS_AUTOGENERATED" = true ] && [ -f "$WRAPPER_SCRIPT" ]; then
  rm -f "$WRAPPER_SCRIPT"
  echo "  → Removed wrapper script: $WRAPPER_SCRIPT"
fi

echo ""
echo "✅ Successfully removed $PARA_TOOL_NAME"
